"""
@file src/db/models/__init__.py
@description Registers every model on Base.metadata.

Every module in this package must be imported here. Alembic compares
`Base.metadata` against the live database, so a model that is not imported is a
table it will believe does not exist -- which is how an autogenerated migration
ends up proposing to drop a table that is very much in use.
"""

from src.db.models.user_account import UserAccount
from src.db.models.memoir import Memoir
from src.db.models.chapter import Chapter
from src.db.models.media_asset import MediaAsset
from src.db.models.memory import Memory
from src.db.models.memory_media import MemoryMedia
from src.db.models.transcript import Transcript
from src.db.models.memoir_participant import MemoirParticipant
from src.db.models.comment import Comment
from src.db.models.memoir_link import MemoirLink
from src.db.models.memoir_export import MemoirExport
from src.db.models.organization_job_run import OrganizationAgentRun, OrganizationJobRun
from src.db.models.organization_proposal import OrganizationActionAudit, OrganizationProposal
from src.db.models.narrative_section import NarrativeSection
from src.db.models.narrative_source import NarrativeSource
from src.db.models.narrative_generation_run import NarrativeGenerationRun

__all__ = [
    "UserAccount",
    "Memoir",
    "Chapter",
    "MediaAsset",
    "Memory",
    "MemoryMedia",
    "Transcript",
    "MemoirParticipant",
    "Comment",
    "MemoirLink",
    "MemoirExport",
    "OrganizationJobRun",
    "OrganizationAgentRun",
    "OrganizationProposal",
    "OrganizationActionAudit",
    "NarrativeSection",
    "NarrativeSource",
    "NarrativeGenerationRun",
]